### PR TITLE
Add the ability to add characters to the set

### PR DESCRIPTION
**Pull request by tchapi**
This PR allows the addition of characters at the start or at the end of the set, automatically adding the interval characters in between so the glyphs table is contiguous

### CODE REVIEW

**Comment by charno** [comment]
@tchapi 

Wow, what a beautiful solution! Much better than my hacky PR! It works form me, and I love that the "Last glyph to export" is automatically updated. Thanks!

Some suggestions / questions:
- I would place the "Add a new character" button in the heading above the glyph table, or somewhere there about. Currently it's in the "load font"-zone, where I think it does not really belong to.
image
- I noticed that in the disabled characters which are added, the `xAdvance` is set to 4 and `yOffset` to 1, and this is also exported. Is this by design or a problem in the export logic? If it's by design I would suggest adding the disabled characters with `xAdvance = 0` and `yOffset = 0`.
- I tried adding a UTF character > 255 (Ā, 0x100). This works and is also correctly exported and can be compiled. When I wondered why you support characters greater than 255 I found a UTF-8 fork of the Adafruit GFX library, nice! But maybe add a check that no character > 0xFFFF can be entered, since `GFXfont.first` and `GFXfont.last` are `uint16_t`.
- I tried adding a big UTF character (⭐, 0x2B50), and my tab froze (most likely since it takes a very long time to add so much characters). I don't know if there is a good solution to this problem.
- It's not relevant for my use case and a bigger change than my one-line-fix suggestions above, but I noticed that I can't add non-printable characters since I have to enter the character itself and can't edit the character code. I've seen in your change that you explicitly check for this (`newCharCode < 32`). In the `Adafruit_GFX::write()` method, this is NOT checked. If it would be possible to enter the keycode directly (in addition to the character?) one could use all characters from 1 to 255 (excluding `\0` which has special meaning in C(++), `\r` (which is ignored in `Adafruit_GFX::write()` and `\n` (which gets special treatment in `Adafruit_GFX::write()`).

Again, thanks a lot for your work. I thought I would do some small, a bit hacky drive-by commit for a corner use case and did not expect to see this properly implemented! :-)

**Comment by tchapi** [comment]
Your suggestions are great ! I've updated a few things — can you have a look ?

**Comment by charno** [comment]
Thanks a lot, that was quick!

I noticed some more things:
- The input field for char code is decimal, not hex. Thus, the length limit should be 5. Invalid characters are catched later anyways.
- When I add new characters that are lower than the currently existing, they are added at the end of the table. This is a problem since in the export the order of the table is respected. I tested with a font beginning on `0x30` ('0'), and added character `0x20` (' '). Since in the export the order of the table is used this leads to incorrect order of the characters in the export. This was probably already present before these new changes, but I didn't catch it then.
- Something curious: In the "in between" characters that are created disabled, the disable-button works inverted (the character is exported disabled when the checkbox is not marked). Was probably also already present before the second commit.
- When the newline or character return characters are present, the output is buggy since the newline is inserted in the comment.
```
 ,{   259,   0,   0,   0,    0,    0 }   // '
'
 ,{   260,   0,   0,   0,    0,    0 }   // ''
 ,{   261,   0,   0,   0,    0,    0 }   // ''
 ,{   262,   0,   0,   0,    0,    0 }   // '
'
```
- generally, in the export for disabled characters the `xAdvance`, `xOffset` and `yOffset` values are still exported. Since the bitmap data is not present in the export anyways it might make sense to set these values to 0 as well? This would prevent inserting empty pixels when a disabled character is used by accident.

Just a thought, and clearly out of scope: How far away from not having a "customizer" but an "editor" where you can create new fonts is this project after these changes? Maybe it's only a dialog to enter font name and first character which initializes the data structures?

**Comment by charno** [comment]
Please have a look at https://github.com/tchapi/Adafruit-GFX-Font-Customiser/pull/18, i added some fixes for the problems I described above.

**Comment by tchapi** [comment]
This is fantastic. Thanks so much for your help on this !

**Comment by charno** [comment]
Thank you for providing this very useful tool! If I find the time I might add some button to create a new, empty font. What do you think about that? Would you be interested in including this feature? With this, this tool would be a full editor which could also be used to create new fonts.

**Comment by tchapi** [comment]
I'm all for it. I think we might need to revamp the JS a bit then, it may become a bit cumbersome otherwise.

**Comment by tchapi** [comment]
PS: I added your handle to https://github.com/tchapi/Adafruit-GFX-Font-Customiser as a contributor. Tell me if you wish to remove this

**Comment by charno** [comment]
Thanks for the merge and for adding me as a contributor! :-)

**Pull request merged**
