### PR TITLE
copy & paste

### PR DESCRIPTION
**Pull request by m4xr1sk**

### CODE REVIEW

**Comment by tchapi** [comment]
Hi
What is the purpose of this PR ?

Thanks

**Comment by m4xr1sk** [comment]
I have added the buttons Copy and paste to each chars.
I Need some special chars with accents for french spanish ect. So I think
to extract the full range of chars from a font the remap the Ones that I
Need in some unused pos




Il sab 29 gen 2022, 12:12 tchap ***@***.***> ha scritto:

**Comment by tchapi** [comment]
It seems that they are a lot of changes in your commits that are not related to that (putting scripts in different files, indentation, etc) so I cannot merge as-is.

Try to extract that specific feature (copy & paste) so the changeset is readable and contained so I can review it

thanks !

**Comment by m4xr1sk** [comment]
Ok, I'll do that.


Il sab 29 gen 2022, 13:59 tchap ***@***.***> ha scritto:

**Comment by m4xr1sk** [comment]
I have reverted the changes then added just the few lines to do the copy and paste. Now the 2 branches are compareble.

**Comment by Lebostein** [comment]
What about a new button like "+ Add new character" but with "+ Add new character as copy of" to create a new character, this time the new character is not empty but is a copy of an existing one.

**Comment by Lebostein** [comment]
> I have reverted the changes then added just the few lines to do the copy and paste. Now the 2 branches are comparable.
What I have to do to get this branch to run?

**Pull request merged**
